version: "2"
services:
  aws-cli:
    container_name: aws-cli
    build: .
    depends_on:
    - s3-cert
    - s3-signature
    environment:
      WAIT_HOSTS: s3-cert:9991, s3-signature:9993
      AWS_DEFAULT_REGION: us-east-1
  s3-cert:
    container_name: s3-cert
    image: scality/s3server
    volumes:
      - ./s3-conf-cert.json:/usr/src/app/config.json
      - ./s3-location-conf-cert.json:/usr/src/app/locationConfig.json
    environment:
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "7000:7000" # s3 server
      - "9991:9991" # data store
  s3-signature:
    container_name: s3-signature
    image: scality/s3server
    volumes:
      - ./s3-conf-signature.json:/usr/src/app/config.json
      - ./s3-location-conf-signature.json:/usr/src/app/locationConfig.json
    environment:
        AWS_ACCESS_KEY_ID: accessKey1
        AWS_SECRET_ACCESS_KEY: verySecretKey1
        AWS_DEFAULT_REGION: us-east-1
    ports:
      - "7001:7001" # s3 server
      - "9993:9993" # data store
