invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://localhost:3011
    functions:
      testResults:
        name: cvs-svc-test-results
        mock: tests/resources/test-results-response.json
      techRecords:
        name: cvs-svc-technical-records-get
        mock: tests/resources/tech-records-response.json
      certGen:
        name: cvs-svc-doc-gen
        mock: tests/resources/cert-gen-response.json
      trailerRegistration:
        name: cvs-svc-trailer-registration
        mock: tests/resources/trailer-registration.json
      testStations:
        name: cvs-svc-test-stations
        mock: tests/resources/test-stations-response.json
      defects:
        name: cvs-svc-defects
        mock: tests/resources/defects-response.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      testResults:
        name: test-results-${BRANCH}
      techRecords:
        name: technical-records-v3-get-${BRANCH}
      techRecordsSearch:
        name: technical-records-v3-search-${BRANCH}
      certGen:
        name: doc-gen-${BRANCH}
      trailerRegistration:
        name: trailer-registration-${BRANCH}
      testStations:
        name: test-stations-${BRANCH}
      defects:
        name: defects-${BRANCH}
network:
  retryAttempts: 3
version:
  trailerRegistration: v1
s3:
  local:
    endpoint: http://localhost:7000
    s3ForcePathStyle: true
  remote: { }
mot:
  documentNames:
    vt20: VT20.pdf
    vt20w: VT20W.pdf
    vt30: VT30.pdf
    vt30w: VT30W.pdf
    vt32ve: VT32VE.pdf
    vt32vew: VT32VEW.pdf
    prs: PRS.pdf
    prsw: PRSW.pdf
    ct20: CT20.pdf
    ct30: CT30.pdf
    vtp20: VTP20.pdf
    vtp20_bilingual: VTP20_BILINGUAL.pdf
    vtp30: VTP30.pdf
    vtp30_bilingual: VTP30_BILINGUAL.pdf
    psv_prs: PSV_PRS.pdf
    psv_prs_bilingual: PSV_PRS_BILINGUAL.pdf
    vtg5: VTG5.pdf
    vtg5_bilingual: VTG5_BILINGUAL.pdf
    vtg5a: VTG5A.pdf
    vtg5a_bilingual: VTG5A_BILINGUAL.pdf
    vtg30: VTG30.pdf
    vtg30_bilingual: VTG30_BILINGUAL.pdf
    hgv_prs: HGV_PRS.pdf;
    hgv_prs_bilingual: HGV_PRS_BILINGUAL.pdf;
    trl_prs: TRL_PRS.pdf;
    trl_prs_bilingual: TRL_PRS_BILINGUAL.pdf;
    rwt: RWT.pdf
    adr_pass: ADR_PASS.pdf;
    iva_fail: IVA30.pdf;
    msva_fail: MSVA30.pdf;
  documentDir: CVS
welsh:
  secret_key:
